CP-4886: Add promition to release to pypi.cloudzero.com after master build
Cloudzero/pyfaaster pull request #47
Opened 2021-02-03 20:30 UTC by boboakes

## Description of the change

Add the semaphore yaml configurations to deploy the newer libraries to pypi.cloudzero.com after a successful build of the master branch.

## Type of change
- [ ] Bug fix
- [x] New feature

## Checklists

### Development
- [ ] All changed code has 80% unit test coverage
- [ ] All changed code has been automatically (smoke test or otherwise) or manually verified in `alfa` (or with a cross namespace setup, e.g. developer namespace for this feature, pointing at shared `alfa` resources)

### Code review 
- [x]  This pull request has a title that includes the ticket # and a short useful summary, e.g. `CP-4051: Create TEMPLATE Feature Repo`.

2021-02-03 20:33 UTC, Tankanow requested changes
@boboakes, this is not right, pyfaaster is actually a public repo published to the public pypi, I think we can use the `make upload` target. (sorry for the short PR comment, I'm on a call)

2021-02-03 21:09 UTC, Tankanow requested changes
Should change the PR title; also 1 change to make

2021-02-03 21:09 UTC, Tankanow commented on .semaphore/release.yml
> +            - make upload
MUST: I think we need those `TWINE` credentials for the push `make TWINE_USERNAME=${PYPI_USERNAME} TWINE_PASSWORD=${PYPI_PASSWORD} upload`

2021-02-03 21:09 UTC, Tankanow commented on .semaphore/release.yml
> +            - make upload
You can use the semaphore secret `PyPi Deployment`, which will put `PYPI_USERNAME` and `PYPI_PASSWORD` into the environment. So you can use the `make` command from the previous comment as is.

2021-02-03 21:14 UTC, boboakes commented on .semaphore/release.yml
> +            - make upload
Done.

2021-02-04 00:12 UTC, Tankanow approved these changes

2021-02-04 13:18 UTC, merged